if: "branch = master"

language: "php"
os:
  - "linux"
dist: "bionic"

jobs:
  include:
    - name: "PHPCS + PHPStan - PHP 7.4"
      php: "7.4"
      env: "WP_VERSION=latest WP_MULTISITE=0"
      install:
        - "composer update"
      script:
        - "vendor/bin/phpcs"
        - "vendor/bin/phpstan analyze --memory-limit=512M"

    - name: "WP 5.2 - PHP 7.2"
      php: "7.2"
      env: "WP_VERSION=5.2 WP_MULTISITE=0"

    - name: "WP latest - PHP 7.0"
      dist: "xenial"
      php: "7.0"
      env: "WP_VERSION=latest WP_MULTISITE=0"

    - name: "WP latest - PHP 8.2"
      php: "8.2"
      env: "WP_VERSION=latest WP_MULTISITE=0"

    - name: "WP nightly - PHP 7.0"
      dist: "xenial"
      php: "7.0"
      env: "WP_VERSION=nightly WP_MULTISITE=0"

    - name: "WP nightly - PHP 8.2"
      php: "8.2"
      env: "WP_VERSION=nightly WP_MULTISITE=0"

  allow_failures:
    - dist: "xenial"
      php: "7.0"
      env: "WP_VERSION=nightly WP_MULTISITE=0"

    - php: "8.2"
      env: "WP_VERSION=nightly WP_MULTISITE=0"

services:
  - "mysql"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"
  - "export PATH=\"$(composer config --absolute --global bin-dir):${PATH}\""

install:
  - |
    if [[ $WP_VERSION == "5.2" ]]; then
      composer require --no-interaction --no-update --ignore-platform-reqs --dev "phpunit/phpunit ^7.5"
    fi
  - composer remove --no-interaction --no-update --dev "phpstan/phpstan"
  - composer remove --no-interaction --no-update --dev "wpsyntex/polylang-phpstan"
  - "composer update"
  - "bash tests/bin/install-wp-tests.sh wordpress_test root \"\" localhost \"${WP_VERSION}\""

script:
  - "vendor/bin/phpunit --verbose"

notifications:
  email:
    on_success: "never"
    on_failure: "change"


